version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: ui-analyzer-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - database-data:/data/db
    networks:
      - ui-analyzer-network

  redis:
    image: redis:latest
    container_name: ui-analyzer-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ui-analyzer-network

  caddy:
    image: caddy:latest
    container_name: ui-analyzer-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - ui-analyzer-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  database-data:
  caddy-data:
  caddy-config:

networks:
  ui-analyzer-network:
