services:
  database:
    image: mongo:latest
    container_name: ui-analyzer-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - database-data:/data/db
    networks:
      - ui-analyzer-network

  redis:
    image: redis:latest
    container_name: ui-analyzer-redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - ui-analyzer-network

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: ui-analyzer-api
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://database:27017/ui-analyzer
      - ANALYZER_API_URL=http://agent:8000
    ports:
      - "3001:3001"
    depends_on:
      - database
      - redis
      - agent
    networks:
      - ui-analyzer-network
      - agent-network

  agent:
    build:
      context: ./apps/agent
      dockerfile: Dockerfile
    container_name: ui-analyzer-agent
    restart: always
    env_file:
      - .env
    # Allocate larger shared memory for Chromium to avoid crashes
    shm_size: "1g"
    expose:
      - "8000"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      # Ensure Chromium runs smoothly in containerized env
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
      - NODE_OPTIONS=--dns-result-order=ipv4first
    # Add necessary kernel capabilities for sandbox if needed; otherwise use --no-sandbox in code
    # cap_add:
    #   - SYS_ADMIN
    networks:
      - agent-network

  caddy:
    image: caddy:latest
    container_name: ui-analyzer-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - ui-analyzer-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  database-data:
  caddy-data:
  caddy-config:

networks:
  ui-analyzer-network:
  agent-network:
  # Note: do not set 'internal: true' so agent has internet access for Playwright
