services:
  database:
    image: mongo:latest
    container_name: ui-analyzer-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - database-data:/data/db
    networks:
      - ui-analyzer-network

  redis:
    image: redis:latest
    container_name: ui-analyzer-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ui-analyzer-network

volumes:
  database-data:

networks:
  ui-analyzer-network: